1. Chat
### 1.1 blocking GET request to chat endpoint
GET {{host}}/blocking/chat?msg="Hello, world!"
### 1.2 streaming GET request to chat endpoint
GET {{host}}/stream/chat?msg="Hello, world!"
### 1.3.1 blocking GET request to chat endpoint with a memory chat
GET {{host}}/blocking/memory/chat?msg="my name is Rui"
### 1.3.2 streaming GET request to chat endpoint with a memory chat
GET {{host}}/blocking/memory/chat?msg="what is my name?"

2. Image
### 2.1 Generate Image
GET {{host}}/blocking/image
### 2.2 Understand Image
POST{{host}}/blocking/image/verification

Content-Type: application/json
{
  "url": "https://cdn.prod.website-files.com/60414b21f1ffcdbb0d5ad688/60fef0f6b3b5c78542284648_Stocksy_txp68bf02bdW49300_Small_3824185.jpg"
}
###

3.Rag
### 3.1 chat with RAG
GET {{host}}/rag?msg="list skipcart team people name"
### 3.2 chat without RAG
GET {{host}}/blocking/chat?msg="list skipcart team people name?"


