spring:
  application:
    name: springai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano #the cheapest model on openai
      embedding:
        options:
          model: text-embedding-3-small #the cheapest embedding model on openai
    vectorstore:
      mongodb:
        collection-name: vector_store
        initialize-schema: true
        index-name: vector_index
        path-name: embedding
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URL}
      database: drive_batch_jobs
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.web.client: DEBUG
server:
  port: 8081