spring:
  application:
    name: springai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano #the cheapest model on openai
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
server:
  port: 8081