Chat

### blocking GET request to chat endpoint
GET http://localhost:8080/blocking/chat?msg="Hello, world!"

### streaming GET request to chat endpoint
GET http://localhost:8080/stream/chat?msg="Hello, world!"

### blocking GET request to chat endpoint with a memory chat
parame
GET http://localhost:8080/blocking/memory/chat?msg="my name is Rui"
###
GET http://localhost:8080/blocking/memory/chat?msg="what is my name?"

Image
###
GET http://localhost:8080/blocking/image/chat"
###


